### ISSUE TITLE
Rename the default branch of this repo from `master` to `main`

### ISSUE THREAD

**Issue by rsimha** [ampproject/storybook-addon-amp#38]
See https://github.com/ampproject/amphtml/issues/32195 for more details

**Comment by alanorozco** [comment]
Unfortunately I don't have privileges to do this. @dvoytenko ?

**Comment by rsimha** [comment]
I just did it for you. Looks like there's no complicated CI config to break. (Please confirm this!)

![image](https://user-images.githubusercontent.com/26553114/114081607-c3013380-987a-11eb-9c34-90f05a6a738e.png)

**Comment by alanorozco** [comment]
> Looks like there's no complicated CI config to break. (Please confirm this!)

LGTM
